### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by yupthatguy** [tuberry/dict-ecdict#1]
$make
curl -kLO https://github.com/skywind3000/ECDICT-ultimate/releases/download/1.0.0/ecdict-ultimate-csv.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   649  100   649    0     0    891      0 --:--:-- --:--:-- --:--:--   891
100 93.7M  100 93.7M    0     0  1763k      0  0:00:54  0:00:54 --:--:-- 2032k
unzip ecdict-ultimate-csv.zip && mv ultimate.csv ecdict.csv
Archive:  ecdict-ultimate-csv.zip
  inflating: ultimate.csv            
python ./ecdicts.py ./ecdict.csv ecdict.txt
dictfmt --utf8 --allchars -s ECDICT -u https://github.com/skywind3000/ECDICT-ultimate -j ecdict < ./ecdict.txt && dictzip ecdict.dict
/bin/sh: 1: dictfmt: not found
make: *** [Makefile:24: ecdict.index] Error 127

**Comment by tuberry** [comment]
> /bin/sh: 1: dictfmt: not found

`dictd` is both dependency and make dependency,  should be installed before building.
